export enum ErrorCommonStrings {
  INTERNAL_SERVER_ERROR = "Internal server error.",
  BAD_INPUT = "BAD_INPUT",
  BAD_REQUEST = "BAD_REQUEST",
  INVALID_USER = "Invalid User",
  INVALID_PASSWORD = "Invalid Password",
  OLD_PASSWORD = "Old Password Is Wrong",
  TOO_MANY_REQUEST = "Too Many Requests",
  UNAUTHORIZED_REQUEST = "UNAUTHORIZED_REQUEST",
  EMAIL_INVALID = "Email Is Invalid",
  USER_NOT_FOUND = "User Not Found",
  INVALID_REQUEST = "Invalid Request",
  UNVERIFIED = "Unverified Email",
  NOT_FOUND = "Not Found",
  NOT_IMPLEMENTED = "Not Implemented",
  ALREADY_EXIST = "Already Exist",
  PLEASE_PROVIDE_ID = "Please provide Id.",
  NOT_AUTHORIZED = "Not Authorized.",
  MISSING_DEVICE = "Missing deviceId in request.",
  DEVICE_NOT_FOUND = "Device not found.",
  DEVICE_ID_REQUIRED = "Device ID is required.",
  DEVICE_ALREADY_EXIST = "Device already registered.",
  NOT_ALLOWED = "MethodNotAllowedError",
  TRANSACTION_FAILED = "transactionFailed",
}
export const localConstant = {
  USER_CREATED: "USER CREATED",
  USER_ALREADY_EXISIT: "USER ALREADY EXISIT",
  USER_NOT_FOUND: "USER NOT FOUND",
  USER_LOGOUT_FAILED: "USER LOGOUT FAILED",
  ADMIN_NOT_CREATED: "ADMIN NOT CREATED",
  INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
  INVALID_PASSWORD: "INVALID PASSWORD",
  USER_NOT_LOGGED_IN: "USER NOT LOGGED IN",
  USER_NOT_CREATED: "USER NOT CREATED",
};
